# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGU2ZDExOWY5OTVhNWE0YTc2MjVjODYxODkzZTk4NjVlMTlkNmYwMWRiYTRlODViZTk5YTlhYmM5ZTViZGJjOWI2ZDU4MTRmOWVmZWM5OTc5MWE1NTJkMzIxZGE0ZmQ2NmM1NDQyYjNkN2VjMzIxYzMxMWFlMDk0Zjk0MzhmMWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
